### ISSUE TITLE
Add seperate deploy button on CMS

### ISSUE THREAD

**Issue by kozr** [nwplus/external-templates#11]
We have a save button right now. But we should also have a separate button that will trigger a redeploy.

Alternatively, figure out deploy logic from CMS.

Should there be a confirmation before it deploys?

**Comment by kozr** [comment]
Haven't started

**Comment by andykwan1124** [comment]
Useful/relevant links:

https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event

https://goobar.io/manually-trigger-a-github-actions-workflow/ <- An example for how to use the dispatch event

**Comment by kozr** [comment]
@vincentchiang1
