### ISSUE TITLE
Statistics Section

### ISSUE THREAD

**Issue by kevin-wu01** [nwplus/external-templates#300]
- [ ] Complete Statistics section
![image](https://user-images.githubusercontent.com/66554168/215015887-c3ecb840-de10-4975-b0c4-850b70f9c904.png)

Statistics Numbers
200+ hackers
45 mentors
30 projects

**Comment by anson1014** [comment]
![image](https://user-images.githubusercontent.com/56494179/216285605-4063de59-74e8-4c3e-b259-25c5c3f92b26.png)

**Comment by kozr** [comment]
@kevin-wu01 do we have stats? Is this the previous year's stats?

**Comment by DonaldKLee** [comment]
> ![image](https://user-images.githubusercontent.com/56494179/216285605-4063de59-74e8-4c3e-b259-25c5c3f92b26.png)

Where can I get my hands on one? 💀

**Comment by kevin-wu01** [comment]
@kozr should be previous year's stats, I'm looking around for them

**Comment by kevin-wu01** [comment]
@kozr updated acs with stats
