### ISSUE TITLE
Implement varible generation from template selection cms/firebase

### ISSUE THREAD

**Issue by kozr** [nwplus/external-templates#55]
As we make new hackathons and use the base templates for footer, navbar, and sponsor. We need to figure out how to load the default variables

**Comment by kozr** [comment]
@yehee

**Comment by kozr** [comment]
This task may be a little difficult so let me know if you need more time.

**Comment by yehee** [comment]
@kozr I've been completely slacking on this ticket, I'll try to get back to it sometime this weekend.
